inherits = "solarized_light"

"ui.background" = {}
# "ui.cursorline" = {}
"ui.gutter" = { bg = "base02" }
"ui.gutter.selected" = { bg = "base03" }
"ui.linenr" = { bg = "base02" }
"ui.linenr.selected" = { fg = "yellow", bg = "base03", modifiers = ["bold"] }
"ui.virtual.indent-guide" = { fg = "base015" }
"ui.virtual.ruler" = { bg = "base0175" }
"ui.cursor.match" = { fg = "base03", bg = "base015" }
"ui.statusline" = { fg = "base03", bg = "base0", modifiers = ["bold"] }
