theme = "solarized_mine"

[editor]
rulers = [80,]
line-number = "relative"
middle-click-paste = false
# Without explicit designation, it doesn't source the global config by default
shell = ["nu", "--config '/home/marco/.config/nushell/config.nu'", "-c"]
bufferline = "multiple"
scroll-lines = 4
cursorline = true
color-modes = true

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "block"

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽" "╎"
skip-levels = 1

# For keymap reference, see <https://docs.helix-editor.com/keymap.html>

[keys.normal]
"C-S-c" = "no_op"
"A-w" = ":w"
"ret" = ["open_below", "collapse_selection", "normal_mode"]
"S-ret" = ["open_above", "collapse_selection", "normal_mode"]

[keys.insert]
"A-q" = "normal_mode" # Maps Alt-X to enter normal mode
# "A-w" = ["normal_mode", ":w", "insert_mode"]
"A-;" = "collapse_selection"
"C-p" = "move_line_up"
"C-n" = "move_line_down"
"C-f" = "move_char_right"
"C-b" = "move_char_left"

[keys.select]
"A-q" = "normal_mode"
